---
# Versão do Docker
docker_version: 19.03.12

docker:
  apt_dep_remove: [docker,docker-engine,docker.io,containerd,runc]
  apt_dep_install: [apt-transport-https,ca-certificates,curl,gnupg-agent,software-properties-common]
  apt_key_url: "https://download.docker.com/linux/{{ ansible_lsb.id.lower() }}/gpg"
  apt_repository: "deb https://download.docker.com/linux/{{ ansible_lsb.id.lower() }} {{ ansible_lsb.codename.lower() }} stable"
