---
- name: Restart haproxy
  service:
    name: haproxy
    state: restarted

- name: Reload haproxy
  service:
    name: haproxy
    state: restarted

- name: Restart keepalived
  service:
    name: keepalived
    state: restarted
